"""init table download tasks and outbox event

Revision ID: 9239191a4f00
Revises: 2ffb2edf6aac
Create Date: 2026-05-12 23:14:13.807310

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9239191a4f00"
down_revision: str | Sequence[str] | None = "2ffb2edf6aac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
